# Generated by Django 3.2.9 on 2021-11-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_petitioner_detail_model_respondents_details_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitioner_detail_model',
            name='petitioner_details',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
