# Generated by Django 3.2.9 on 2021-11-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_petitioner_detail_model_petitioner_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitioner_detail_model',
            name='petitioner_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
